import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Senior Frontend Engineer',
    company: 'FANAP',
    logo: '/images/careers/fanap.webp',
    location: 'Tehran',
    location_type: 'On-site',
    type: 'Fulltime',
    start_date: '2023-12',
    end_date: null,
    industry: 'E-learning',
    link: 'https://fanap.ir',
    down: 'Not launched yet',
  },
  {
    position: 'Lead Frontend Engineer',
    company: 'ChartBox.ir',
    logo: '/images/careers/chartbox.png',
    location: 'Tehran',
    location_type: 'On-site',
    type: 'Fulltime',
    start_date: '2022-05',
    end_date: '2023-12',
    industry: 'Fintech',
    link: 'https://ChartBox.ir',
    down: 'Not launched yet',
  },
  {
    position: 'Frontend Engineer',
    company: 'Tutify',
    logo: '/images/careers/tutify.jpg',
    location: 'Tehran',
    location_type: 'On-site',
    type: 'Fulltime',
    start_date: '2020-10',
    end_date: '2022-05',
    industry: 'E-learning',
    link: 'https://tutify.me',
    down: 'Downed due to financial problems',
  },
];
